db: biu
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  datasource:
      name: dev
      url: jdbc:mysql://121.42.145.216:3306/biu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
  #    password: ENC(jLsYb6iWiRX88MJ5HfzP9w==)
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      # druid 配置: https://github.com/alibaba/druid/wiki/
      initialSize: 1
      minIdle: 1
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      # 配置监控统计拦截的filters，stat用于监控界面，'wall'用于防火墙防御sql注入, slf4j用于druid记录sql日志
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: false
#  redis:
#    host: localhost
#    port: 6379
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://121.42.145.216:3306/biu?characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
logging:
  path: ./logs
  level:
    com.abc.dao: debug

# dubbo
dubbo :
  application :
    id: app-web
    name : app-web
#  registry :
#    id: app-web
  protocol:
    port: -1
    name: dubbo

#    status: server
  registry:
#    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
#    id: admin-provider
#  scan:
#    basePackages: com.melody.service
  #scan:
    #basePackages: com.ysla.web.controller
# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true